### ISSUE TITLE
SOAP API Changed to SSL

### ISSUE THREAD

**Issue by SirLancelotDuLac** [jonathanmedd/BricksetModule#18]
Hi there

The scripts stoped working because the SOAP api owner changed to https

Thanks

**Comment by jonathanmedd** [comment]
Thanks for reporting that. Even if I update the code to use the https URL they are still returning an http URL to use for the connection:

$BricksetConnection.WebService



SoapVersion                          : Default
AllowAutoRedirect                    : False
CookieContainer                      :
ClientCertificates                   : {}
EnableDecompression                  : False
UserAgent                            : Mozilla/4.0 (compatible; MSIE 6.0; MS Web Services Client Protocol 4.0.30319.42000)
Proxy                                :
UnsafeAuthenticatedConnectionSharing : False
Credentials                          :
UseDefaultCredentials                : False
ConnectionGroupName                  :
PreAuthenticate                      : False
Url                                  : http://brickset.com/api/v2.asmx
RequestEncoding                      :
Timeout                              : 100000
Site                                 :
Container                            :

So I'll need to implement an additional workaround in the meantime.

**Comment by jonathanmedd** [comment]
Updated to version 1.3.3, issue is fixed in that version.
