### ISSUE TITLE
Update for BrickSet API v3

### ISSUE THREAD

**Issue by tpcarman** [jonathanmedd/BricksetModule#20]
Hi Jonathan,

BrickSet API v2 is now retired and a new [API v3](https://brickset.com/tools/webservices/v3) released.

Would it be possible to update your module to use the new API?

Cheers,
Tim

**Comment by jowo1711** [comment]
Hi Jonathan,

An update to API v3 will be much appricated.

Cheers, 
John

**Comment by jonathanmedd** [comment]
Thanks for the interest. I had another look at this back in December and discovered that the API v3 also supports REST which means the lack of SOAP support in PowerShell 6+ is not an issue.

Started work on this on the `feature/api-v3` branch.....

**Comment by jonathanmedd** [comment]
All done and published to the PowerShell gallery as v2.0.1 :-)

**Comment by tpcarman** [comment]
Awesome work @jonathanmedd. Thank you.

**Comment by tpcarman** [comment]
Now I can start playing around with my idea for a BrickSet catalog 😃  
![image](https://user-images.githubusercontent.com/15333667/104791484-f76ed180-57ee-11eb-9008-c0aa849786f5.png)

**Comment by jowo1711** [comment]
Works like a charm!!!!
@jonathanmedd. Thanks for the effort.
